### PR TITLE
GH-177: Return json object with error

### LINKED ISSUE #177: [FEATURE PROPOSAL] Fetch should throw an error if the response fails
Currently the implementation of the adapter does not provide any information when fetch fail for an 404 being hard to track or redirect in the application.

My proposal is adjust the current https://github.com/lexich/redux-api/blob/master/src/adapters/fetch.js#L27 to follow the idea of this issue https://github.com/github/fetch/issues/155

Which means that our current implementation will look like
```
export default function (fetch) {
  return (url, opts)=> fetch(url, opts).then(resp=>
    toJSON(resp).then((data)=> {
      if (resp.status >= 200 && resp.status < 300) {
        return data;
      } else if (resp.status >= 400) {
         const error = new Error(response.statusText || response.status)
         error.response = response
         return Promise.reject(error)
      } else {
        return Promise.reject(data);
      }
    }));
}
```

### PR DESCRIPTION
**Pull request by EduardoAC**
Currently, there is not information what it was the problem using response information provided by fetch API.

The data provided initially will be the status code and text from the response.

Fix #177

### CODE REVIEW

File: src/adapters/fetch.js [hunk 1]
```diff
@@ -23,8 +23,11 @@ export default function (fetch) {
     toJSON(resp).then((data)=> {
       if (resp.status >= 200 && resp.status < 300) {
         return data;
+      } else if (resp.status >= 400) {
```
Comment (lexich) [inline src/adapters/fetch.js]: I think that the best way to refactor code.
```javascript
if (resp.status >= 400) { 
   return Promise.reject({ status: resp.status, statusText: resp.statusText });
} else {
   return toJSON(resp).then(.......)
}
``

Comment (EduardoAC) [reply src/adapters/fetch.js]: 👍  Makes sense what you propose. My mindset was on group all the statusCode

**Comment by lexich** [comment]
@EduardoAC Good work. Version 0.11.1
