### PR TITLE
WIP: Fix promise not resolved when using `crud`

### LINKED ISSUE #126: POST doesn't resolve promise if I use crud
I've defined an api this way
```
    url: '/api/clients/:clientId/object',
    crud: true,
    options: {
      credentials: 'include',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
    },
```

in `mapDispatchToProps`
```
addObject: (clientId, data) =>
    dispatch(api.actions.jsonObject.post({clientId}, {body: JSON.stringify(data)})),
```

in component
```
const afas = this.props.addObject(this.props.clientId, object).then((data) => {
        debugger;
        console.log(data);
      });
````

the promise callback is never hit. 

If I define the API with `method: 'POST'`, it does. Why is that?

### PR DESCRIPTION
**Pull request by LoicMahieu**
Fix #126 

Totally `WIP`. Tests are missing...

### CODE REVIEW

File: src/actionFn.js [hunk 1]
```diff
@@ -253,12 +253,12 @@ export default function actionFn(url, name, options, ACTIONS={}, meta={}) {
...
         } else {
           // if helper alias is synchronous
+          const [pathvars, params] = helpersResult;
           fastApply(
-            sync ? fn.sync : fn, null, helpersResult.concat(callback)
+            sync ? fn.sync : fn, null, [pathvars, params, callback]
           )(dispatch, getState);
         }
       });
-      result.catch(none);
```
Comment (lexich) [inline src/actionFn.js]: Here is very important place. We catch all uncatch error and it prevent a lot of errors.

File: src/actionFn.js [hunk 2]
```diff
@@ -253,12 +253,12 @@ export default function actionFn(url, name, options, ACTIONS={}, meta={}) {
           });
         } else {
           // if helper alias is synchronous
+          const [pathvars, params] = helpersResult;
           fastApply(
-            sync ? fn.sync : fn, null, helpersResult.concat(callback)
+            sync ? fn.sync : fn, null, [pathvars, params, callback]
```
Comment (lexich) [inline src/actionFn.js]: Why it's better?

File: test/actionFn_spec.js [hunk 3]
```diff
@@ -705,13 +705,13 @@ describe("actionFn", function() {
     const expectedEvent = [{
       type: "actionFetch",
       syncing: false,
-      request: { pathvars: { id: "overwrite" }, params: {} }
+      request: { pathvars: { id: "overwrite" }, params: undefined }
```
Comment (lexich) [inline test/actionFn_spec.js]: Why do you use undefined in test, may be delete params?

**Comment by lexich** [comment]
Oh, work in progress. Any way I pointed to some important place. And anyway thx for your interesting to project. Good job 👍
